### ISSUE TITLE
Fix Linting and uncomment .github/workflows/pr.yml:26-27

### ISSUE THREAD

**Issue by vosi** [thenewboston-developers/thenewboston-python#27]
**Bug Description**
There are a number of styles and linting problems, that should be fixed;
After that .github/workflows/pr.yml:26-27 should be uncommented

**Steps to Reproduce**
Follow the Readme file and run `flake8 .`

**Expected behavior**
`flake8 .` should pass without errors

**Actual behavior**
`flake8 .` fails

blocked by #26

**Comment by samutoljamo** [comment]
There are a few constructors missing a docstring. Do you want to ignore that error or make docstrings for the constructors?

**Comment by vosi** [comment]
i'd prefer to have strings for "constructors"
