### ISSUE TITLE
Dockerize Local Development Environment

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-python#31]
Use Docker Compose to create a local development network including:
- Primary Validator
- Confirmation Validator
- Bank

Developers should be able run a mini network (Banks and Validators) in their local environments without having to manually configure every node.

**Comment by anamritraj** [comment]
Can I take a stab at it? Please assign this to me :)

**Comment by buckyroberts** [comment]
@anamritraj my bad, I meant to assign @vosi to it yesterday

**Comment by odetolataiwo** [comment]
hello @buckyroberts  did @vosi solve this issue?

**Comment by vosi** [comment]
@odetolataiwo this is done, check Validator or Bank repos

**Comment by tawanike** [comment]
@vosi What is your account number?
