### ISSUE TITLE
Celery service is failed.

### ISSUE THREAD

**Issue by navidhrangon** [thenewboston-developers/thenewboston-python#34]
**Bug Description**

Job for celery.service failed because the control process exited with error code.

**Steps to Reproduce**
1. Create service for celery:
`sudo nano /etc/systemd/system/celery.service`

[Unit]
Description=Bank Celery Service
After=network.target

[Service]
Type=forking
User=deploy
EnvironmentFile=/etc/bank/celery.conf
WorkingDirectory=/var/www/Bank
ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'
ExecStop=/bin/sh -c '${CELERY_BIN} multi stopwait ${CELERYD_NODES} \
  --pidfile=${CELERYD_PID_FILE}'
ExecReload=/bin/sh -c '${CELERY_BIN} multi restart ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'

[Install]
WantedBy=multi-user.target

2. Reload systemd and enable both services:
        `sudo systemctl daemon-reload && sudo systemctl enable api && sudo systemctl enable celery`

**Expected behavior**
I should not get any error message.
**Actual behavior**
Job for celery.service failed because the control process exited with error code.
See "systemctl status celery.service" and "journalctl -xe" for details.

**OS and Browser**
 - OS: NAME="Ubuntu"
          VERSION="20.04.1 LTS (Focal Fossa)"

**Account Number**
d41e28d025992108c7a846a28ce975587b999808606ebb659e0303fd85d9fc1a

**Comment by nax3t** [comment]
I also experienced this issue. Changing requirements/production.txt and requirements/base.in to use version 0.0.24 resolved the Celery issue, but now I'm running into an error with the `python3 manage.py initialize_validator` command: `ModuleNotFoundError: No module named 'thenewboston.argparser'`
Running on Ubuntu 18.04 with DO
