### ISSUE TITLE
Generate documentation for the codebase using sphinx

### ISSUE THREAD

**Issue by sbalasa** [thenewboston-developers/thenewboston-python#36]
Once the codebase grows to a greater size keeping tracks of things will be difficult, so generating documentation will be handy.

**Comment by AbhayAysola** [comment]
I'd like to work on this one.

**Comment by sbalasa** [comment]
Sure

**Comment by AbhayAysola** [comment]
@sbalasa I can't figure out how to get this working. Since this is meant to be used as a library for other thenewboston projects, django throws errors that the app is not initialized and whatnot when sphinx is trying to import the files for autodoc. Do you have any suggestions to fix this issue?

**Comment by sbalasa** [comment]
@AbhayAysola - You need `sphinx-apidoc`, hmmm take a look at this: https://www.freecodecamp.org/news/sphinx-for-django-documentation-2454e924b3bc

**Comment by AbhayAysola** [comment]
I tried using sphinx-apidoc, I will check that article out and get back to you.

**Comment by AbhayAysola** [comment]
So in that article, it says that we need to set the `DJANGO_SETTINGS_MODULE`, but I can't find any settings file in the project. @sbalasa

**Comment by sbalasa** [comment]
@AbhayAysola - Sorry was super busy this week, okay create a pull request, and I will fix this issue for you and update the changes to your branch directly, after that you may just beautify the files :)

**Comment by AbhayAysola** [comment]
@sbalasa No problem. I will definitely do that. Thanks for your help :)

**Comment by AbhayAysola** [comment]
Also, I didn't quite get what you meant by beautifying `index.rst`. It looks pretty good to me. Do I need to change the theme?

**Comment by sbalasa** [comment]
> @sbalasa No problem. I will definitely do that. Thanks for your help :)

Most Welcome :)

**Comment by sbalasa** [comment]
> Also, I didn't quite get what you meant by beautifying `index.rst`. It looks pretty good to me. Do I need to change the theme?

Nevermind typo It got pasted here by mistake 😅

**Comment by AbhayAysola** [comment]
So should I make a pull request or do you want to? Since it was your work I think you should get paid. Also, could you give me a rundown of how you got it to work. Thanks again @sbalasa

**Comment by sbalasa** [comment]
No worries, Just go ahead with the pull request, just review the output if everything is working. Welcome @AbhayAysola

**Comment by AbhayAysola** [comment]
Hmm ok I'll do that
