### ISSUE TITLE
ERROR: thenewboston 0.0.29 has requirement setuptools==50.3.2, but you'll have setuptools 45.2.0 which is incompatible.

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-python#40]
Remove setuptools from requirements.

```
ERROR: thenewboston 0.0.29 has requirement setuptools==50.3.2, but you'll have setuptools 45.2.0 which is incompatible.
```

**Comment by nax3t** [comment]
Temporary solution until setuptools is removed from the requirements:
`pip3 install setuptools==50.3.2`
and 
`pip3 install testresources` (this also broke the install and was noted as a dependency of launchpadlib)

**Comment by vosi** [comment]
setuptools can't be removed from requirements, since this is a lib that help us to publish pip package

**Comment by vosi** [comment]
also, i'm not quite sure how you've got that error, could you provide some "steps to reproduce" guide? @buckyroberts

**Comment by buckyroberts** [comment]
Can't remember what I did. Closing and will re-open if I come across it again.
