### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-python#6]
There is some remaining code in this repo left over from old logic, previous features, etc... Remove all code from `/thenewboston` package that is not used in any of the following repos:

- https://github.com/thenewboston-developers/thenewboston-python (this repo)
- https://github.com/thenewboston-developers/Bank
- https://github.com/thenewboston-developers/Validator

**Comment by hunterlogan1399** [comment]
I'll take a look into this to get started
